
export const GET_TODO_LSIT = 'GET_TODO_LSIT';
export const GET_TODO_LSIT_LOADING = 'GET_TODO_LSIT_LOADING';
export const GET_TODO_LSIT_SUCCESS = 'GET_TODO_LSIT_SUCCESS';
export const GET_TODO_LSIT_ERROR = 'GET_TODO_LSIT_ERROR';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_TODO_LOADING = 'REMOVE_TODO_LOADING';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';

export const CHECK_TODO = 'CHECK_TODO';
export const CHECK_TODO_LOADING = 'CHECK_TODO_LOADING';
export const CHECK_TODO_SUCCESS = 'CHECK_TODO_SUCCESS';
export const CHECK_TODO_ERROR = 'CHECK_TODO_ERROR';

export const GET_TODO_TOTAL_RECORD = 'GET_TODO_TOTAL_RECORD';
export const GET_TODO_TOTAL_RECORD_LOADING = 'GET_TODO_TOTAL_RECORD_LOADING';
export const GET_TODO_TOTAL_RECORD_SUCCESS = 'GET_TODO_TOTAL_RECORD_SUCCESS';
export const GET_TODO_TOTAL_RECORD_ERROR = 'GET_TODO_TOTAL_RECORD_ERROR';
