
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const GET_TODO_LIST_LOADING = 'GET_TODO_LIST_LOADING';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_ERROR = 'GET_TODO_LIST_ERROR';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_TODO_LOADING = 'REMOVE_TODO_LOADING';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';

export const CHECK_TODO = 'CHECK_TODO';
export const CHECK_TODO_LOADING = 'CHECK_TODO_LOADING';
export const CHECK_TODO_SUCCESS = 'CHECK_TODO_SUCCESS';
export const CHECK_TODO_ERROR = 'CHECK_TODO_ERROR';

export const DONE_TODO = 'DONE_TODO';
export const DONE_TODO_LOADING = 'DONE_TODO_LOADING';
export const DONE_TODO_SUCCESS = 'DONE_TODO_SUCCESS';
export const DONE_TODO_ERROR = 'DONE_TODO_ERROR';

export const GET_TODO_TOTOAL = 'GET_TODO_TOTOAL';
export const GET_TODO_TOTOAL_LOADING = 'GET_TODO_TOTOAL_LOADING';
export const GET_TODO_TOTOAL_SUCCESS = 'GET_TODO_TOTOAL_SUCCESS';
export const GET_TODO_TOTOAL_ERROR = 'GET_TODO_TOTOAL_ERROR';

export const DONE_TODO_TOTOAL = 'DONE_TODO_TOTOAL';
export const DONE_TODO_TOTOAL_LOADING = 'DONE_TODO_TOTOAL_LOADING';
export const DONE_TODO_TOTOAL_SUCCESS = 'DONE_TODO_TOTOAL_SUCCESS';
export const DONE_TODO_TOTOAL_ERROR = 'DONE_TODO_TOTOAL_ERROR';

export const FLUSH_TODOS_LIST = 'FLUSH_TODOS_LIST';
export const FLUSH_DONO_TODOS_LIST = 'FLUSH_DONO_TODOS_LIST';
